#ifndef _LITEX_MMC_H_
#define _LITEX_MMC_H_

#include <linux/litex.h>

/* register sizes (in bytes) */
#define LITEX_MMC_SDPHY_CARDDETECT_SIZE  1
#define LITEX_MMC_SDPHY_CLOCKERDIV_SIZE  2
#define LITEX_MMC_SDPHY_INITIALIZE_SIZE  1
#define LITEX_MMC_SDPHY_WRITESTATUS_SIZE 1

#define LITEX_MMC_SDCORE_CMDARG_SIZE     4
#define LITEX_MMC_SDCORE_CMDCMD_SIZE     4
#define LITEX_MMC_SDCORE_CMDSND_SIZE     1
#define LITEX_MMC_SDCORE_CMDRSP_SIZE    16
#define LITEX_MMC_SDCORE_CMDEVT_SIZE     1
#define LITEX_MMC_SDCORE_DATAEVT_SIZE    1
#define LITEX_MMC_SDCORE_BLKLEN_SIZE     2
#define LITEX_MMC_SDCORE_BLKCNT_SIZE     4

/* sdreader */
#define LITEX_MMC_SDBLK2MEM_BASE_SIZE    8
#define LITEX_MMC_SDBLK2MEM_LEN_SIZE     4
#define LITEX_MMC_SDBLK2MEM_ENA_SIZE     1
#define LITEX_MMC_SDBLK2MEM_DONE_SIZE    1
#define LITEX_MMC_SDBLK2MEM_LOOP_SIZE    1

/* sdwriter */
#define LITEX_MMC_SDMEM2BLK_BASE_SIZE    8
#define LITEX_MMC_SDMEM2BLK_LEN_SIZE     4
#define LITEX_MMC_SDMEM2BLK_ENA_SIZE     1
#define LITEX_MMC_SDMEM2BLK_DONE_SIZE    1
#define LITEX_MMC_SDMEM2BLK_LOOP_SIZE    1
#define LITEX_MMC_SDMEM2BLK_OFF_SIZE     4

/* sdirq */
#define LITEX_MMC_SDIRQ_STATUS_SIZE	 4
#define LITEX_MMC_SDIRQ_PENDING_SIZE	 4
#define LITEX_MMC_SDIRQ_ENABLE_SIZE	 4

/* register offsets (w.r.t. region base addr.) */
#define LITEX_MMC_SDPHY_CARDDETECT_OFF  0x00
#define LITEX_MMC_SDPHY_CLOCKERDIV_OFF  0x04
#define LITEX_MMC_SDPHY_INITIALIZE_OFF  0x08
#define LITEX_MMC_SDPHY_WRITESTATUS_OFF 0x0C

#define LITEX_MMC_SDCORE_CMDARG_OFF     0x00
#define LITEX_MMC_SDCORE_CMDCMD_OFF     0x04
#define LITEX_MMC_SDCORE_CMDSND_OFF     0x08
#define LITEX_MMC_SDCORE_CMDRSP_OFF     0x0C
#define LITEX_MMC_SDCORE_CMDEVT_OFF     0x1C
#define LITEX_MMC_SDCORE_DATAEVT_OFF    0x20
#define LITEX_MMC_SDCORE_BLKLEN_OFF     0x24
#define LITEX_MMC_SDCORE_BLKCNT_OFF     0x28

/* sdreader */
#define LITEX_MMC_SDBLK2MEM_BASE_OFF    0x00
#define LITEX_MMC_SDBLK2MEM_LEN_OFF     0x08
#define LITEX_MMC_SDBLK2MEM_ENA_OFF     0x0C
#define LITEX_MMC_SDBLK2MEM_DONE_OFF    0x10
#define LITEX_MMC_SDBLK2MEM_LOOP_OFF    0x14

/* sdwriter */
#define LITEX_MMC_SDMEM2BLK_BASE_OFF    0x00
#define LITEX_MMC_SDMEM2BLK_LEN_OFF     0x08
#define LITEX_MMC_SDMEM2BLK_ENA_OFF     0x0C
#define LITEX_MMC_SDMEM2BLK_DONE_OFF    0x10
#define LITEX_MMC_SDMEM2BLK_LOOP_OFF    0x14
#define LITEX_MMC_SDMEM2BLK_OFF_OFF     0x18

/* sdirq */
#define LITEX_MMC_SDIRQ_STATUS_OFF	0x00
#define LITEX_MMC_SDIRQ_PENDING_OFF     0x04
#define LITEX_MMC_SDIRQ_ENABLE_OFF      0x08

#endif /* _LITEX_MMC_H_ */
