#ifndef _LITEX_MMC_H_
#define _LITEX_MMC_H_

#include <linux/litex.h>

/* register sizes (in bytes) */
#define LITEX_MMC_SDPHY_CARDDETECT_SIZE  1
#define LITEX_MMC_SDPHY_CLOCKERDIV_SIZE  2
#define LITEX_MMC_SDPHY_INITIALIZE_SIZE  1
#define LITEX_MMC_SDPHY_WRITESTATUS_SIZE 1

#define LITEX_MMC_SDCORE_CMDARG_SIZE     4
#define LITEX_MMC_SDCORE_CMDCMD_SIZE     4
#define LITEX_MMC_SDCORE_CMDSND_SIZE     1
#define LITEX_MMC_SDCORE_CMDRSP_SIZE    16
#define LITEX_MMC_SDCORE_CMDEVT_SIZE     1
#define LITEX_MMC_SDCORE_DATAEVT_SIZE    1
#define LITEX_MMC_SDCORE_BLKLEN_SIZE     2
#define LITEX_MMC_SDCORE_BLKCNT_SIZE     4

/* sdreader */
#define LITEX_MMC_SDBLK2MEM_BASE_SIZE    8
#define LITEX_MMC_SDBLK2MEM_LEN_SIZE     4
#define LITEX_MMC_SDBLK2MEM_ENA_SIZE     1
#define LITEX_MMC_SDBLK2MEM_DONE_SIZE    1
#define LITEX_MMC_SDBLK2MEM_LOOP_SIZE    1

/* sdwriter */
#define LITEX_MMC_SDMEM2BLK_BASE_SIZE    8
#define LITEX_MMC_SDMEM2BLK_LEN_SIZE     4
#define LITEX_MMC_SDMEM2BLK_ENA_SIZE     1
#define LITEX_MMC_SDMEM2BLK_DONE_SIZE    1
#define LITEX_MMC_SDMEM2BLK_LOOP_SIZE    1
#define LITEX_MMC_SDMEM2BLK_OFF_SIZE     4

/* register offsets (w.r.t. region base addr.) */
#define LITEX_MMC_SDPHY_CARDDETECT_OFF  0x00
#define LITEX_MMC_SDPHY_CLOCKERDIV_OFF \
	_next_reg_off(LITEX_MMC_SDPHY_CARDDETECT_OFF, \
		      LITEX_MMC_SDPHY_CARDDETECT_SIZE)
#define LITEX_MMC_SDPHY_INITIALIZE_OFF \
	_next_reg_off(LITEX_MMC_SDPHY_CLOCKERDIV_OFF, \
		      LITEX_MMC_SDPHY_CLOCKERDIV_SIZE)
#define LITEX_MMC_SDPHY_WRITESTATUS_OFF \
	_next_reg_off(LITEX_MMC_SDPHY_INITIALIZE_OFF, \
		      LITEX_MMC_SDPHY_INITIALIZE_SIZE)

#define LITEX_MMC_SDCORE_CMDARG_OFF  0x00
#define LITEX_MMC_SDCORE_CMDCMD_OFF \
	_next_reg_off(LITEX_MMC_SDCORE_CMDARG_OFF, \
		      LITEX_MMC_SDCORE_CMDARG_SIZE)
#define LITEX_MMC_SDCORE_CMDSND_OFF \
	_next_reg_off(LITEX_MMC_SDCORE_CMDCMD_OFF, \
		      LITEX_MMC_SDCORE_CMDCMD_SIZE)
#define LITEX_MMC_SDCORE_CMDRSP_OFF \
	_next_reg_off(LITEX_MMC_SDCORE_CMDSND_OFF, \
		      LITEX_MMC_SDCORE_CMDSND_SIZE)
#define LITEX_MMC_SDCORE_CMDEVT_OFF \
	_next_reg_off(LITEX_MMC_SDCORE_CMDRSP_OFF, \
		      LITEX_MMC_SDCORE_CMDRSP_SIZE)
#define LITEX_MMC_SDCORE_DATAEVT_OFF \
	_next_reg_off(LITEX_MMC_SDCORE_CMDEVT_OFF, \
		      LITEX_MMC_SDCORE_CMDEVT_SIZE)
#define LITEX_MMC_SDCORE_BLKLEN_OFF \
	_next_reg_off(LITEX_MMC_SDCORE_DATAEVT_OFF, \
		      LITEX_MMC_SDCORE_DATAEVT_SIZE)
#define LITEX_MMC_SDCORE_BLKCNT_OFF \
	_next_reg_off(LITEX_MMC_SDCORE_BLKLEN_OFF, \
		      LITEX_MMC_SDCORE_BLKLEN_SIZE)

/* sdreader */
#define LITEX_MMC_SDBLK2MEM_BASE_OFF   0x00
#define LITEX_MMC_SDBLK2MEM_LEN_OFF \
	_next_reg_off(LITEX_MMC_SDBLK2MEM_BASE_OFF, \
		      LITEX_MMC_SDBLK2MEM_BASE_SIZE)
#define LITEX_MMC_SDBLK2MEM_ENA_OFF \
	_next_reg_off(LITEX_MMC_SDBLK2MEM_LEN_OFF, \
		      LITEX_MMC_SDBLK2MEM_LEN_SIZE)
#define LITEX_MMC_SDBLK2MEM_DONE_OFF \
	_next_reg_off(LITEX_MMC_SDBLK2MEM_ENA_OFF, \
		      LITEX_MMC_SDBLK2MEM_ENA_SIZE)
#define LITEX_MMC_SDBLK2MEM_LOOP_OFF \
	_next_reg_off(LITEX_MMC_SDBLK2MEM_DONE_OFF, \
		      LITEX_MMC_SDBLK2MEM_DONE_SIZE)

/* sdwriter */
#define LITEX_MMC_SDMEM2BLK_BASE_OFF   0x00
#define LITEX_MMC_SDMEM2BLK_LEN_OFF \
	_next_reg_off(LITEX_MMC_SDMEM2BLK_BASE_OFF, \
		      LITEX_MMC_SDMEM2BLK_BASE_SIZE)
#define LITEX_MMC_SDMEM2BLK_ENA_OFF \
	_next_reg_off(LITEX_MMC_SDMEM2BLK_LEN_OFF, \
		      LITEX_MMC_SDMEM2BLK_LEN_SIZE)
#define LITEX_MMC_SDMEM2BLK_DONE_OFF \
	_next_reg_off(LITEX_MMC_SDMEM2BLK_ENA_OFF, \
		      LITEX_MMC_SDMEM2BLK_ENA_SIZE)
#define LITEX_MMC_SDMEM2BLK_LOOP_OFF \
	_next_reg_off(LITEX_MMC_SDMEM2BLK_DONE_OFF, \
		      LITEX_MMC_SDMEM2BLK_DONE_SIZE)
#define LITEX_MMC_SDMEM2BLK_OFF_OFF \
	_next_reg_off(LITEX_MMC_SDMEM2BLK_LOOP_OFF, \
		      LITEX_MMC_SDMEM2BLK_LOOP_SIZE)

#endif /* _LITEX_MMC_H_ */
