#ifndef _LITEX_LITEETH_H_
#define _LITEX_LITEETH_H_

#include <linux/litex.h>

/* register sizes */
#define LITEETH_WRITER_SLOT_SIZE        1
#define LITEETH_WRITER_LENGTH_SIZE      4
#define LITEETH_WRITER_ERRORS_SIZE      4
#define LITEETH_WRITER_EV_STATUS_SIZE   1
#define LITEETH_WRITER_EV_PENDING_SIZE  1
#define LITEETH_WRITER_EV_ENABLE_SIZE   1
#define LITEETH_READER_START_SIZE       1
#define LITEETH_READER_READY_SIZE       1
#define LITEETH_READER_LEVEL_SIZE       1
#define LITEETH_READER_SLOT_SIZE        1
#define LITEETH_READER_LENGTH_SIZE      2
#define LITEETH_READER_EV_STATUS_SIZE   1
#define LITEETH_READER_EV_PENDING_SIZE  1
#define LITEETH_READER_EV_ENABLE_SIZE   1
#define LITEETH_PREAMBLE_CRC_SIZE       1
#define LITEETH_PREAMBLE_ERRORS_SIZE    4
#define LITEETH_CRC_ERRORS_SIZE         4

#define LITEETH_PHY_CRG_RESET_SIZE      1
#define LITEETH_MDIO_W_SIZE             1
#define LITEETH_MDIO_R_SIZE             1

/* register offsets */
#define LITEETH_WRITER_SLOT_OFF       0x00
#define LITEETH_WRITER_LENGTH_OFF     0x04
#define LITEETH_WRITER_ERRORS_OFF     0x08
#define LITEETH_WRITER_EV_STATUS_OFF  0x0C
#define LITEETH_WRITER_EV_PENDING_OFF 0x10
#define LITEETH_WRITER_EV_ENABLE_OFF  0x14
#define LITEETH_READER_START_OFF      0x18
#define LITEETH_READER_READY_OFF      0x1C
#define LITEETH_READER_LEVEL_OFF      0x20
#define LITEETH_READER_SLOT_OFF       0x24
#define LITEETH_READER_LENGTH_OFF     0x28
#define LITEETH_READER_EV_STATUS_OFF  0x2C
#define LITEETH_READER_EV_PENDING_OFF 0x30
#define LITEETH_READER_EV_ENABLE_OFF  0x34
#define LITEETH_PREAMBLE_CRC_OFF      0x38
#define LITEETH_PREAMBLE_ERRORS_OFF   0x3C
#define LITEETH_CRC_ERRORS_OFF        0x40

#define LITEETH_PHY_CRG_RESET_OFF     0x00
#define LITEETH_MDIO_W_OFF            0x04
#define LITEETH_MDIO_R_OFF            0x0C

#endif /* _LITEX_LITEETH_H_ */
