#ifndef _LITEX_LITEETH_H_
#define _LITEX_LITEETH_H_

#include <linux/litex.h>

/* register sizes */
#define LITEETH_WRITER_SLOT_SIZE        1
#define LITEETH_WRITER_LENGTH_SIZE      4
#define LITEETH_WRITER_ERRORS_SIZE      4
#define LITEETH_WRITER_EV_STATUS_SIZE   1
#define LITEETH_WRITER_EV_PENDING_SIZE  1
#define LITEETH_WRITER_EV_ENABLE_SIZE   1
#define LITEETH_READER_START_SIZE       1
#define LITEETH_READER_READY_SIZE       1
#define LITEETH_READER_LEVEL_SIZE       1
#define LITEETH_READER_SLOT_SIZE        1
#define LITEETH_READER_LENGTH_SIZE      2
#define LITEETH_READER_EV_STATUS_SIZE   1
#define LITEETH_READER_EV_PENDING_SIZE  1
#define LITEETH_READER_EV_ENABLE_SIZE   1
#define LITEETH_PREAMBLE_CRC_SIZE       1
#define LITEETH_PREAMBLE_ERRORS_SIZE    4
#define LITEETH_CRC_ERRORS_SIZE         4

#define LITEETH_PHY_CRG_RESET_SIZE      1
#define LITEETH_MDIO_W_SIZE             1
#define LITEETH_MDIO_R_SIZE             1

/* register offsets */
#define LITEETH_WRITER_SLOT_OFF  0x00
#define LITEETH_WRITER_LENGTH_OFF \
	_next_reg_off(LITEETH_WRITER_SLOT_OFF, \
		      LITEETH_WRITER_SLOT_SIZE)
#define LITEETH_WRITER_ERRORS_OFF \
	_next_reg_off(LITEETH_WRITER_LENGTH_OFF, \
		      LITEETH_WRITER_LENGTH_SIZE)
#define LITEETH_WRITER_EV_STATUS_OFF \
	_next_reg_off(LITEETH_WRITER_ERRORS_OFF, \
		      LITEETH_WRITER_ERRORS_SIZE)
#define LITEETH_WRITER_EV_PENDING_OFF \
	_next_reg_off(LITEETH_WRITER_EV_STATUS_OFF, \
		      LITEETH_WRITER_EV_STATUS_SIZE)
#define LITEETH_WRITER_EV_ENABLE_OFF \
	_next_reg_off(LITEETH_WRITER_EV_PENDING_OFF, \
		      LITEETH_WRITER_EV_PENDING_SIZE)
#define LITEETH_READER_START_OFF \
	_next_reg_off(LITEETH_WRITER_EV_ENABLE_OFF, \
		      LITEETH_WRITER_EV_ENABLE_SIZE)
#define LITEETH_READER_READY_OFF \
	_next_reg_off(LITEETH_READER_START_OFF, \
		      LITEETH_READER_START_SIZE)
#define LITEETH_READER_LEVEL_OFF \
	_next_reg_off(LITEETH_READER_READY_OFF, \
		      LITEETH_READER_READY_SIZE)
#define LITEETH_READER_SLOT_OFF \
	_next_reg_off(LITEETH_READER_LEVEL_OFF, \
		      LITEETH_READER_LEVEL_SIZE)
#define LITEETH_READER_LENGTH_OFF \
	_next_reg_off(LITEETH_READER_SLOT_OFF, \
		      LITEETH_READER_SLOT_SIZE)
#define LITEETH_READER_EV_STATUS_OFF \
	_next_reg_off(LITEETH_READER_LENGTH_OFF, \
		      LITEETH_READER_LENGTH_SIZE)
#define LITEETH_READER_EV_PENDING_OFF \
	_next_reg_off(LITEETH_READER_EV_STATUS_OFF, \
		      LITEETH_READER_EV_STATUS_SIZE)
#define LITEETH_READER_EV_ENABLE_OFF \
	_next_reg_off(LITEETH_READER_EV_PENDING_OFF, \
		      LITEETH_READER_EV_PENDING_SIZE)
#define LITEETH_PREAMBLE_CRC_OFF \
	_next_reg_off(LITEETH_READER_EV_ENABLE_OFF, \
		      LITEETH_READER_EV_ENABLE_SIZE)
#define LITEETH_PREAMBLE_ERRORS_OFF \
	_next_reg_off(LITEETH_PREAMBLE_CRC_OFF, \
		      LITEETH_PREAMBLE_CRC_SIZE)
#define LITEETH_CRC_ERRORS_OFF \
	_next_reg_off(LITEETH_PREAMBLE_ERRORS_OFF, \
		      LITEETH_PREAMBLE_ERRORS_SIZE)

#define LITEETH_PHY_CRG_RESET_OFF  0x00
#define LITEETH_MDIO_W_OFF \
	_next_reg_off(LITEETH_PHY_CRG_RESET_OFF, \
		      LITEETH_PHY_CRG_RESET_SIZE)
#define LITEETH_MDIO_R_OFF \
	_next_reg_off(LITEETH_MDIO_W_OFF, \
		      LITEETH_MDIO_W_SIZE)

#endif /* _LITEX_LITEETH_H_ */
