# SPDX-License-Identifier: GPL-2.0
generic-y += early_ioremap.h
generic-y += flat.h
generic-y += kvm_para.h
generic-y += spinlock_types.h
generic-y += spinlock.h
generic-y += user.h
generic-y += vmlinux.lds.h
